activation: tanh
initial_weights_regularizer: false
initialization: Glorot normal
learning_rate: 0.001
num_dense_layers: 4
num_dense_nodes: 50
num_domain: 500
num_boundary: 200
num_test: 1000
resampling: true
w_res: 1
w_bc0: 1
n_ins: 2
n_anchor_points: 0