model_properties:
  L0: 0.07
  tauf: 1800.0
  k: 0.6
  rho: 1000.0
  c: 4186.0
  W: 0.6
  h: 10.0
  Troom: 21.5
  Tmax: 32.0
  Ty10: 22.28
  Ty20: 26.67
  Ty30: 21.5
  K: 10.0
  delta: 6.0
  activation: "tanh"
  initial_weights_regularizer: true
  initialization: "Glorot uniform"
  iterations: 100000
  LBFGS: false
  learning_rate: 0.0001
  num_dense_layers: 6
  num_dense_nodes: 92
  num_domain: 2000
  num_boundary: 4000
  num_initial: 1600
  num_test: 10000
  resampling: true
  resampler_period: 100
  w_res: 1.0
  w_bc0: 1.0
  w_bc1: 1.0
  w_ic: 1.0
  beta: 1.0
  SAR_0: 0.0
  PD: 0.03
  x0: 0.004

model_parameters:
  lam: 100.0
  upsilon: 5.0
  W0: 0.2
  W1: 0.3
  W2: 0.4
  W3: 0.5
  W4: 0.6
  W5: 0.7
  W6: 0.8
  W7: 0.9
  n_obs: 8
  delta_sys: 1.0

experiment:
  type: "measurement"
  run_matlab: false
  run_wandb: false
  name: "cooling_meas_2"

output:
  base_dir: ${hydra:runtime.output_dir}
  save_figures: true

output_dir: ${hydra:run.dir}

plot:
  rescale: true
  colors:
    observers: ["C0", "C1", "C2", "C3", "C4", "C5", "C6", "C7"]
    system: "C9"
    mm_obs: "gold"
    measuring_points: ["blue", "aquamarine", "salmon", "rosybrown"]
    losses: ["lightgreen", "khaki", "paleturquoise", "thistle", "darkred", "grey"]

  linestyles:
    observers: ["-", "-.", "-", "-.", "--", "-", "--", "-"]
    groundtruths: "--"
    mm_obs: ":"
    system: "-."

cooling_meas_1:
  date: "20240930_1"
  start_min: 41
  y1_0: 22.28
  y2_0: 26.67
  y3_0: 21.5
  delta: 6.0

cooling_meas_2:
  date: "20240930_3"
  start_min: 30
  y1_0: 22.84
  y2_0: 28.6
  y3_0: 21.5
  delta: 8.0