model_properties:
  L0: 0.07
  tf: 1800.0
  k: 0.6
  rho: 1000.0
  c: 4186.0
  incr_fact: 1.0
  wb: 0.0033
  h: 10.0
  Troom: 21.5
  Tmax: 32.0
  Ty10: 21.5
  Ty20: 30.2
  Ty30: 21.5
  Tgt0: 31.5
  theta10: 0.12762
  theta20: 0.67619
  theta30: 0.0
  thetagt0: 0.95238
  thetagt10: 0.95238
  oig: 2.46
  af: tanh
  iwr: false
  init: Glorot normal
  optimizer: L-BFGS
  iters: 3000
  iters_lbfgs: 15000
  lr: 0.001
  depth: 4
  width: 50
  nres: 500
  nb: 200
  ntest: 1000
  resampling: true
  resampler_period: 100
  wres: 1
  wbc0: 1
  beta: 0.9
  pwr_fact: 0.0
  SAR_0: 50.0
  PD: 0.025
  x0: 0.001
  a1: 18.992037
  a2: 34185.6666667
  a3: 0.0
  a4: 1.9415887
  a5: 1.1666667
  cc: 27.736982
  b1: -2711.46326
  b2: 2710.1258
  b3: 0.78889
  b4: 0.67619
  c1: -1.33746
  c2: 0.78889
  c3: 0.67619
  nins: 4
  seed: 500
  sigma: 1.0
  nanc: 0
model_parameters:
  lam: 1
  upsilon: 100.0
  wbmin: 6.3e-05
  wbmax: 0.00165
  wb0: 6.3e-05
  wb1: 0.0001
  wb2: 0.00016
  wb3: 0.000255
  wb4: 0.000407
  wb5: 0.000649
  wb6: 0.001035
  wb7: 0.00165
  wbsys: 0.0005
  wbobs: 0.000255
  wbindex: 3
  nobs: 1
  xgt: 0.01
  xw: 0.025
  xgt1: 0.04
  Xgt: 0.14286
  Xw: 0.35714
  Xgt1: 0.57143
plot:
  show: true
  show_obs: false
  show_gt: false
  show_sys: true
  rescale: true
  display_every: 200
experiment:
  ground_truth: true
  gt_path: /Users/guglielmocappellini/Desktop/research/code/pinns-bioheat-experiments/tests/gt_k/
  simulation: false
  inverse: false
  run: meas_cool_2
  wandb: false
  wandb_name: opt_alfa
experiment_type:
  import_data: false
  save_pickle: true
  simulation:
    Ty10: 21.5
    Ty20: 30.2
    Ty30: 21.5
    Tgt20: 31.5
    lam: 1
    upsilon: 100.0
  meas_cool_1:
    title: Cooling 1
    date: '20240930_1'
    string: meas_cool_1
    start_min: 43
    end_min: 73
    Ty10: 22.17
    Tgt10: 24.23
    Tgt20: 28.4
    Ty20: 27.43
    Ty30: 21.5
    Tfl: 22.01
    r1: 0.0005
    lam: 10.0
    upsilon: 100.0
    n_obs: 64
  meas_cool_2:
    title: Cooling 2
    date: '20240930_3'
    string: meas_cool_2
    start_min: 30
    end_min: 60
    Ty10: 22.84
    Ty20: 28.6
    Ty30: 21.5
    Tgt10: 24.56
    Tgt20: 29.46
    Tfl: 21.63
    r1: 0.001
    lam: 10.0
    upsilon: 100.0
    n_obs: 64
  agar_1:
    date: 240124
    string: agar_1
    start_min: 0
    end_min: 240
    title: Agar 1
    phantom: B
  agar_2:
    date: 240125
    string: agar_2
    start_min: 0
    end_min: 30
    title: Agar 2
    phantom: B
  agar_3:
    date: 240125b
    string: agar_3
    start_min: 0
    end_min: 240
    title: Agar 3
    phantom: B
  agar_4:
    date: 240130
    string: agar_4
    start_min: 0
    end_min: 240
    title: Agar 4
    phantom: B
  agar_5:
    date: 240202
    string: agar_5
    start_min: 0
    end_min: 240
    title: Agar 5
    phantom: B
run:
  dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
output_dir: /Users/guglielmocappellini/Desktop/research/code/pinns-bioheat-experiments/outputs/2025-03-01/22-39-42
