# Configuration for model properties
model_properties:
  L0: 0.07
  tauf: 1800.0
  k: 0.6
  rho: 1000.0
  c: 4186.0
  W: 0.8
  h: 10.0
  Troom: 22.89
  Tmax: 32.0
  K: 10.0
  delta: 0.0
  activation: "tanh"
  initial_weights_regularizer: true
  initialization: "Glorot uniform"
  iterations: 100000
  LBFGS: false
  learning_rate: 0.0001
  num_dense_layers: 6
  num_dense_nodes: 92
  num_domain: 1000
  num_boundary: 2000
  num_initial: 800
  num_test: 10000
  resampling: true
  resampler_period: 100
  w_res: 1.0
  w_bc0: 1.0
  w_bc1: 1.0
  w_ic: 1.0

# Configuration for model parameters (applied after training)
model_parameters:
  lam: 5.0
  upsilon: 150.0
  W0: 0.1
  W1: 0.14
  W2: 0.25
  W3: 0.4
  W4: 0.8
  W5: 1.3
  W6: 1.8
  W7: 2.5
  Ty20: 32.0
  Twater: 22.89
  n_obs: 8
  delta_sys: 4.0

# Experiment type: can be either 'simulation' or 'measurement', with different observers (3 or 8)
experiment:
  type: "simulation"  # Choose between 'simulation' or 'measurement'
  run_matlab: true
  run_wandb: false
  name: "cooling_free_8Obs"

# Output directory management
output:
  base_dir: "${hydra:runtime.output_dir}"  # Hydra auto-generates subdirectories per run
  save_figures: true

output_dir: ${hydra:run.dir}
# Plot configuration
plot:
  colors: ["C0", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9" ]
  linestyles:
    observers: "-"
    groundtruths: "--"
    mm_obs: ":"
    system: "-."

