model_properties:
  L0: 0.07
  tauf: 3600.0
  k: 0.6
  rho: 1000.0
  c: 4186.0
  W: 0.001651
  h: 10.0
  Troom: 21.5
  Tmax: 32.0
  Ty10: 21.5
  Ty20: 32.0
  Ty30: 21.5
  K: 4.6
  activation: tanh
  initial_weights_regularizer: true
  initialization: Glorot normal
  iterations: 10000
  LBFGS: false
  learning_rate: 0.001
  num_dense_layers: 4
  num_dense_nodes: 50
  num_domain: 8000
  num_boundary: 4800
  num_initial: 3200
  num_test: 20000
  resampling: true
  resampler_period: 100
  w_res: 1
  w_bc0: 1
  w_bc1: 1
  w_ic: 1
  beta: 0.9
  pwr_fact: 0.0
  SAR_0: 50.0
  PD: 0.025
  x0: 0.001
  b1: 2.0789
  b2: 1.0
  direct: false
model_parameters:
  lam: 50
  upsilon: 50
  W0: 6.3e-05
  W1: 0.0006
  W2: 0.003303
  W3: 0.0014
  W4: 0.001651
  W5: 0.0021
  W6: 0.0026
  W7: 0.001207
  W_sys: 6.3e-05
  W_obs: 6.3e-05
  n_obs: 1
  gt1_0: 24.44
  gt2_0: 29.25
  x_y2: 0
  x_gt2: 0.01
  x_gt1: 0.04
  x_y1: 0.07
  loss_weights:
  - 1
  - 1
  - 1
  - 1
plot:
  rescale: true
  display_every: 500
  colors:
    measuring_points:
    - '#F7CAC9'
    - '#6B5B95'
    - '#88B04B'
    - '#FF6F61'
    - '#92A8D1'
    losses:
    - '#D2691E'
    - '#4682B4'
    - '#9ACD32'
    - '#FF6347'
    - '#FFD700'
    - '#FF1493'
  linestyles:
    measuring_points:
    - '-'
    - -.
    - '-'
    - -.
    - --
  entities:
    system:
      color: C3
      label: System PINNs
      linestyle: '-'
      linewidth: 1.2
      alpha: 1.0
    multi_observer:
      color: gold
      label: MultiObs PINNs
      linestyle: ':'
      linewidth: 1.2
      alpha: 1.0
    observers:
      color:
      - C0
      - C1
      - C2
      - C9
      - C4
      - C5
      - C6
      - C7
      label:
      - Obs 0 PINNs
      - Obs 1 PINNs
      - Obs 2 PINNs
      - Obs 3 PINNs
      - Obs 4 PINNs
      - Obs 5 PINNs
      - Obs 6 PINNs
      - Obs 7 PINNs
      linestyle:
      - '-'
      - -.
      - '-'
      - -.
      - --
      - '-'
      - --
      - '-'
      linewidth:
      - 1.2
      - 1.2
      - 1.2
      - 1.2
      - 1.2
      - 1.2
      - 1.2
      - 1.2
      alpha:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    system_gt:
      color: C3
      label: System MATLAB
      linestyle: --
      linewidth: 1.0
      alpha: 0.8
    theory:
      color: purple
      label: Theory
      linestyle: --
      linewidth: 1.0
      alpha: 1.0
    bound:
      color: chocolate
      label: Bound
      linestyle: -.
      linewidth: 1.0
      alpha: 1.0
    multi_observer_gt:
      color: gold
      label: MultiObs MATLAB
      linestyle: --
      linewidth: 1.0
      alpha: 0.8
    observers_gt:
      color:
      - C0
      - C1
      - C2
      - C9
      - C4
      - C5
      - C6
      - C7
      label:
      - Obs 0 MATLAB
      - Obs 1 MATLAB
      - Obs 2 MATLAB
      - Obs 3 MATLAB
      - Obs 4 MATLAB
      - Obs 5 MATLAB
      - Obs 6 MATLAB
      - Obs 7 MATLAB
      linestyle:
      - ':'
      - ':'
      - ':'
      - ':'
      - ':'
      - ':'
      - ':'
      - ':'
      linewidth:
      - 1.2
      - 1.2
      - 1.2
      - 1.2
      - 1.2
      - 1.2
      - 1.2
      - 1.2
      alpha:
      - 0.7
      - 0.7
      - 0.7
      - 0.7
      - 0.7
      - 0.7
      - 0.7
      - 0.7
experiment:
  import_data: false
  save_pickle: false
  run_matlab: true
  simulation: true
  run_wandb: false
  check_system: false
  type:
    cooling:
      h: 10.0
      pwr_fact: 0.0
      threshold: 0.5
      show_y3: false
      simulation:
        y1_0: 21.5
        gt1_0: 24.44
        gt2_0: 29.25
        y2_0: 32.0
        y3_0: 21.5
      meas_1:
        title: Cooling 1
        date: '20240930_1'
        string: cooling_meas_1
        start_min: 41
        end_min: 71
        y1_0: 22.28
        gt1_0: 24.44
        gt2_0: 29.25
        y2_0: 26.67
        y3_0: 21.5
        K: 50.0
        b2: 0.0236
        b3: 0.3091
      meas_2:
        title: Cooling 2
        date: '20240930_3'
        string: cooling_meas_2
        start_min: 30
        end_min: 60
        y1_0: 22.84
        gt1_0: 24.56
        gt2_0: 29.46
        y2_0: 28.6
        y3_0: 21.5
        K: 50.0
        b2: 0.0079
        b3: -0.0491
    heating:
      h: 238.0
      pwr_fact: 0.4
      threshold: 50
      show_y3: true
      meas_1:
        title: Heating 1
        date: '20240522_1'
        string: heating_meas_1
        start_min: 4
        end_min: 34
        y1_0: 21.88
        gt1_0: 22.67
        gt2_0: 26.3
        y2_0: 26.76
        y3_0: 25.8
        b2: 0.0236
        b3: 0.3091
      meas_2:
        title: Heating 2
        date: '20240927_3'
        string: heating_meas_2
        start_min: 105
        end_min: 135
        y1_0: 22.87
        gt1_0: 23.48
        gt2_0: 24.24
        y2_0: 24.71
        y3_0: 23.98
        b2: 0.0236
        b3: 0.3091
      meas_3:
        title: Heating 3
        date: '20240930_1'
        string: heating_meas_3
        start_min: 5
        end_min: 35
        y1_0: 21.61
        gt1_0: 21.5
        gt2_0: 21.74
        y2_0: 23.24
        y3_0: 23.82
        b2: 0.0236
        b3: 0.3091
    antenna_characterization:
      pwr_fact: 1.0
      threshold: 50
      show_y3: false
      title: Antenna characterization
      date: '20240930_3'
      string: antenna_characterization
      start_min: 0
      end_min: 17
      y1_0: 22.56
      gt1_0: 22.99
      gt2_0: 23.73
      y2_0: 24.0
      y3_0: 23.26
run:
  dir: ./pinns-bioheat-experiments/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
output_dir: /Users/guglielmocappellini/Desktop/phd/code/pinns-bioheat-experiments/outputs/2024-11-14/12-28-57
