# Configuration for model properties
model_properties:
  L0: 0.07
  tauf: 2400.0
  k: 0.6
  rho: 1000.0
  c: 4186.0
  W: 0.8
  h: 238.0
  Troom: 21.5
  Tmax: 32.0
  Ty20: 22.55
  Twater: 22.55
  K: 10.0
  delta: 2.0
  activation: "tanh"
  initial_weights_regularizer: true
  initialization: "Glorot uniform"
  iterations: 100000
  LBFGS: false
  learning_rate: 0.0001
  num_dense_layers: 6
  num_dense_nodes: 92
  num_domain: 2000
  num_boundary: 4000
  num_initial: 1600
  num_test: 10000
  resampling: true
  resampler_period: 100
  w_res: 1.0
  w_bc0: 1.0
  w_bc1: 1.0
  w_ic: 1.0
  beta: 1.0
  SAR_0: 0.38
  PD: 0.03
  x0: 0.004


# Configuration for model parameters (applied after training)
model_parameters:
  lam: 100.0
  upsilon: 1.0
  W0: 0.3
  W1: 0.3
  W2: 0.4
  W3: 0.5
  W4: 0.6
  W5: 0.7
  W6: 0.8
  W7: 0.9
  n_obs: 3
  delta_sys: 0.4

# Experiment type: can be either 'simulation' or 'measurement', with different observers (3 or 8)
experiment:
  type: "ground_truth"  # Choose between 'simulation' or 'measurement'
  run_matlab: true
  run_wandb: false
  name: "source"

# Output directory management
output:
  base_dir: "${hydra:runtime.output_dir}"  # Hydra auto-generates subdirectories per run
  save_figures: true

output_dir: ${hydra:run.dir}
# Plot configuration
plot:
  rescale: true
  colors: 
    observers: ["C0", "C1", "C2", "C3", "C4", "C5", "C6", "C7"]
    system: "C9"
    mm_obs: "gold"
    measuring_points: ["blue", "aquamarine", "salmon", "rosybrown"]
    losses: ["lightgreen", "khaki", "paleturquoise", "thistle", "darkred", "grey"]
  linestyles:
    observers: ["-","-.","-","-.","--","-","--","-"]
    groundtruths: "--"
    mm_obs: ":"
    system: "-."

