properties:
  L0: 0.07
  tf: 1800.0
  k: 0.65
  rho: 1595.0
  rhob: 1000.0
  c: 4186.0
  cb: 3600.0
  h: 10.0
  cc: 27.736982
  beta: 0.9
  pwrfact: 0.0
  SAR0: 50.0
  PD: 0.0136
  x0: 0.001
temps:
  Troom: 21.5
  Tmax: 32.0
  Ty10: 21.5
  Ty20: 30.2
  Ty30: 21.5
  Tgt0: 31.5
  Tgt10: 31.5
hp:
  af: tanh
  iwr: false
  init: Glorot normal
  optimizer: adam
  iters: 3000
  iters_lbfgs: 15000
  lr: 0.001
  depth: 4
  width: 50
  nres: 500
  nb: 200
  ntest: 1000
  resampling: true
  resampler_period: 100
  wres: 1
  wbc0: 1
  nins: 2
  seed: 500
  nanc: 0
pdecoeff:
  a1: 27.9621222
  a2: 27138.4615385
  a3: 0.0
  a4: 3.5702945
  a5: 1.0769231
  b1: -1.7982
  b2: 0.07732
  b3: 0.89231
  b4: 0.82857
  c1: null
  c2: null
  c3: null
  oig: 2.46
  y10: 0.0
  y20: 0.82857
  y30: 0.0
  thetagt0: 0.95238
  thetagt10: 0.95238
  incrfact: 1.0
  wb: 6.3e-05
parameters:
  ag: 1
  ups: 100.0
  wbmin: 6.3e-05
  wbmax: 0.00165
  wb0: 6.3e-05
  wb1: 0.0001
  wb2: 0.00016
  wb3: 0.000255
  wb4: 0.000407
  wb5: 0.000649
  wb6: 0.001035
  wb7: 0.00165
  wbsys: 6.3e-05
  wbobs: 0.000255
  obsindex: 3
  nobs: 0
  xgt: 0.01
  xw: 0.025
  xgt1: 0.04
  Xgt: 0.14286
  Xw: 0.35714
  Xgt1: 0.57143
  drdiff: 0.1677324
  drexact: 0.1491204
  c0: 0.3085594
plot:
  show: true
  show_obs: false
  plot_gt: false
  show_gt: true
  show_sys: true
  rescale: true
  display_every: 200
experiment:
  inverse: false
  run: simulation_system
  wandb: true
  wandb_name: opt_ai_direct
run:
  dir: /Users/guglielmocappellini/Desktop/research/code/pinns-bioheat-experiments/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
output_dir: /Users/guglielmocappellini/Desktop/research/code/pinns-bioheat-experiments/outputs/2025-03-10/18-18-37
testloss: 0.0782
runtime: 0.0
